# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab3540786fb47c669290eee4ba436ce641d4fe402bca8af661564374a6b0f251dae302536f2db7abe40d558fea8cf978cc05f5b8ca947b1934d48b5b1ca6a9f

test:
  secret_key_base: c195ceaa0c518f3237126e6ef6253564769784bdf80feb8f12698b9a6d42952639eeda75443ff2aacd643b1f1dee09cb89784663314efd908c62dbde1e810b5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
